### ISSUE TITLE
Add a new organization to ROR: State Scientific Institution "Ukrainian Institute of Scientific and Technical Expertise and Information"

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#104]
Summary of request: Add a new organization to ROR

Name of organization: State Scientific Institution "Ukrainian Institute of Scientific and Technical Expertise and Information"
Website: http://www.ukrintei.ua/
Link to publications: http://www.ukrintei.ua/page/publikaciyi
Wikipedia page: https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D1%96%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%82_%D0%BD%D0%B0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE-%D1%82%D0%B5%D1%85%D0%BD%D1%96%D1%87%D0%BD%D0%BE%D1%97_%D0%B5%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D1%82%D0%B8%D0%B7%D0%B8_%D1%82%D0%B0_%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D1%97
Wikidata ID: https://www.wikidata.org/wiki/Q12100495
ISNI ID: https://isni.org/isni/0000000098247458
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Державна наукова установа «Український інститут науково-технічної експертизи та інформації».   УкрІНТЕІ
Acronym/abbreviation: 
Related organizations: https://ror.org/03bra4w96 (parent)
City: 180, Antonovicha street, Kiev, 03150, Ukraine
Country: 
Other information about this request:

**Comment by KellyStathis** [comment]
I agree this meets criteria for inclusion in ROR. For the name, looking at similar organizations' entries, ROR sometimes includes the phrase "State Institution" at the front, e.g.: https://ror.org/04zjdjw13. We may want to include this either as the primary name, or in an alias, for consistency.

For related organizations: the parent institution is the Ministry of Education and Science (per http://www.uintei.kiev.ua/en/page/about-ukristei), which has a ROR ID: https://ror.org/03bra4w96. Relatedly, I think the Ministry of Education and Science record should also be updated to have the country name in the primary name field, otherwise it is hard to find.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05wf2rt56 in release v1.0.
