### ISSUE TITLE
Modify the information in an existing ROR record: University of Illinois at Rockford - https://ror.org/02437s643

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1250]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Illinois at Rockford
ROR ID: https://ror.org/02437s643
Which part of the record needs to be changed? Names, Aliases
Description of change: There is no U of I at Rockford. There is a Rockford campus of the University of Illinois Chicago.

Update: change.name==University of Illinois Chicago, Rockford campus; add.aliases==University of Illinois at Rockford; delete.relationships==https://ror.org/05e94g991; replace.links==https://www.uillinois.edu;$

Related organizations: https://ror.org/02mpq6x41 (parent)

**Comment by adambuttrick** [comment]
See #1234 for original context. There doesn't appear to be a standard form for this campus' name. All its colleges use differing forms. See links to colleges [here](https://www.uillinois.edu/cms/One.aspx?portalId=1324&pageId=348087) for details. Existing name has affiliation usage (e.g. https://doi.org/10.1592/phco.22.7.436.33667; https://doi.org/10.1177/106002808802200914; https://doi.org/10.1016/j.fertnstert.2009.07.1677), so preserving as an alias.

**Comment by arthurpsmith** [comment]
I think the main question would be whether this campus should ever have been given an independent ID, given our general policy on campuses. Assuming we do hang on to it with its own ID though, then yes the parent should be changed as recommended here.
The other metadata on this is also wrong or inconsistent. The website does not resolve. The ISNI is for "College of Medicine at Rockford" or "University of Illinois at Chicago College of Medicine at Rockford". Maybe instead of representing the campus we should just change this ID to represent the college of medicine, which does seem clear? The other entities on the campus are also medical-related so that might be justifiable. Although we don't generally create separate ID's for medical schools.

After thinking a bit about this, my strongest opinion is that we should deprecate this ID and point to University of Illinois at Chicago (https://ror.org/02mpq6x41) as the successor.

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
