### ISSUE TITLE
Add a new organization to ROR: 
 
Multiscale Bioimaging

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#200]
Summary of request: Add a new organization to ROR

Name of organization: Multiscale Bioimaging
Website: https://mbexc.de/
Link to publications: https://mbexc.uni-goettingen.de/literature
Organization type: Education
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q96756740
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: EXC 2067: Multiscale Bioimaging: from Molecular Machines to Networks of Excitable Cells
Acronym/abbreviation: MBExC
Related organizations: https://ror.org/01y9bpm73 (parent)
City: Göttingen
Country: Germany
Other information about this request:

**Comment by arthurpsmith** [comment]
While this meets some of our criteria, I believe it does not qualify for a ROR at this time for the following reasons:
1. It is a research project within the University of Göttingen, and when used as an affiliation the university is always included as part of the affiliation from the cases I've looked at; in fact authors usually directly reference the university (perhaps with a department), and not this project, as their affiliation. They do seem to acknowledge this project as a funding source.
2. I don't believe these are intended to be long-term organizations; this one has existed only since 2019. More information on the German "Clusters of Excellence" (there are 57 right now) here: https://www.research-in-germany.org/en/research-landscape/excellence-universities/clusters-of-excellence.html

*However* we do have at least 2 of the Clusters of Excellence in ROR right now, so on the grounds that we have included these before it could be argued this one qualifies also:
https://ror.org/05tbc9841 - Cluster of Excellence "Matters of Activity. Image Space Material" at Humboldt University Berlin
https://ror.org/034waa237 - Cluster of Excellence on Plant Sciences at University of Dusseldorf.

**Comment by MSpenger** [comment]
I primarily agree with Arthur. This topic should also be discussed within the ROR cummunity.

Here are some mor details on Clusters of Excellence
- they have a duration of seven years (with possibility of renewal) and are associated with a host institution
- information from the DFG "Clusters of excellence enable German university locations to establish internationally visible, competitive research and training facilities, thereby enhancing scientific networking and cooperation among the participating institutions. Clusters of excellence should form an important part of a university's strategic and thematic planning, significantly raise its profile and reflect its considered long-term priorities." https://www.dfg.de/en/research_funding/programmes/excellence_initiative/clusters_excellence/index.html

there are already some more Clusters of Excellence in ROR, which would make a case for including "Multiscale Bioimaging" :
- https://ror.org/05874db82 - Excellence Cluster Universe -> replaced by ORIGINS (https://ror.org/010wkny21)
- https://ror.org/04c4bwh63 - Cologne Excellence Cluster on Cellular Stress Responses in Aging Associated Diseases
- https://ror.org/02wkzzr31 - Nanoscale Microscopy and Molecular Physiology of the Brain Cluster of Excellence 171
- https://ror.org/025z3z560 - Munich Cluster for Systems Neurology

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05xy1nn52 in release v1.0.
