### ISSUE TITLE
Add a new organization to ROR: 
 
Asociación Panameña para el Avance de la Ciencia

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#203]
Summary of request: Add a new organization to ROR

Name of organization: Asociación Panameña para el Avance de la Ciencia
Website: http://www.apanac.org.pa/
Link to publications: http://www.apanac.org.pa/es/listado-de-congresos
Organization type: Nonprofit
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: APANAC Panama
Acronym/abbreviation: APANAC
Related organizations: SENACYT https://ror.org/03gat5t60 (related), INDICASAT https://ror.org/04ngphv84 (related), GORGAS https://ror.org/019ev8b82 (related)
City: Panamá
Country: Panamá
Other information about this request: Es una entidad privada sin ánimo de lucro, cuya misión es trabajar por el fomento de la ciencia y tecnología como bases del desarrollo nacional, fundada el 4 de enero de 1985 y que desde 1995 organiza el Congreso Nacional de Ciencia y Tecnología que  es la conferencia científica-tecnológica más importante de Panamá.

**Comment by arthurpsmith** [comment]
This appears to be the principle general scientific society in Panama. I couldn't find Wikipedia or Wikidata or ISNI entries, but it has been around since 1985 and has over 100 members, a substantial group of original founders, runs an annual conference, etc. I think this qualifies as an independent research organization and should have an entry in ROR.

**Comment by carlyrobinson** [comment]
I agree that this is within scope and should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05mhn0t19 in release v1.0.
