### ISSUE TITLE
Add a new organization to ROR: IT-Gruppe Geisteswissenschaften

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#23]
Summary of request: Add a new organization to ROR

Name of organization: IT-Gruppe Geisteswissenschaften
Website: https://www.itg.uni-muenchen.de/index.html
Link to publications: List of projects: https://www.itg.uni-muenchen.de/projekte/oeffentlich/index.html ; DOI (example): https://doi.org/10.5282/ubm/epub.42418 ; there are many project-specific DOIs for the projects shown in the first link.
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Acronyms: ITG
Aliases: 
Labels: LMU Center for Digital Humanities*English
Acronym/abbreviation:
Related organizations: https://ror.org/05591te55 (parent)
City: Munich
Country: Germany
Geonames ID: 2867714
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:  ITG is mainly an institution inside LMU, but also is part of many projects that go beyond the institution boundaries. For clear identification of projects and initiatives, this identifier would also be used. It was a request from the researchers as well as the ITG staff to have a specific identifier for the affiliation.

**Comment by mariagould** [comment]
This is a legacy issue from early days of the curation pilot in 2020 and we were not able to make a clear determination on scope at the time. I am reinstating it for review now. @MSpenger I believe you initially created this request, so can you confirm whether the request is still valid, and if so, how we would evaluate it given our current criteria and workflows?

**Comment by MSpenger** [comment]
Regarding our recent recommendations, this entry would also be out of scope, as the ITG is part of LMU Munich. Half of the criteria from our "Checklist for evaluating new organizations" apply. 

However, many of the hosted projects are collaborations between different institutions, so that would qualify for ROR. The ITG also has its own DOI prefix. An overview can be found here: https://www.itg.uni-muenchen.de/projekte/oeffentlich/index.html and an example for a journal-like publication is here: http://www.kit.gwi.uni-muenchen.de/
