### ISSUE TITLE
Add a new organization to ROR: Agencia Regional para o Desenvolvimento da Investigacao Tecnologia e Inovacao

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2470]
Summary of request: Add a new organization to ROR

Name of organization: Agencia Regional para o Desenvolvimento da Investigacao Tecnologia e Inovacao
Website:  https://www.arditi.pt
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID: Q98077015
ISNI ID: 0000 0004 6363 8474
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ARDITI
Aliases: 
Labels:
Related organizations: 
City:  Funchal
Country: Portugal
Geonames ID: 2267827
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
State research sponsor and development agency for the Autonomous Region of Madeira in Portugal. Affiliation usage is somewhat limited, but this is otherwise fine to add.

Publication affiliation usage: https://doi.org/10.1093/plankt/fbac057; https://doi.org/10.14411/fp.2021.003; https://doi.org/10.3389/fmars.2021.645578; https://doi.org/10.3389/fmars.2021.688248; https://doi.org/10.1016/j.scitotenv.2021.148652

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01y0vz750 in release v1.21.
