### ISSUE TITLE
Modify the information in an existing ROR record: 
Charité - Universitätsmedizin Berlin https://ror.org/001w7jn25


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#258]
Summary of request: Modify the information in an existing ROR record

Name of organization: Charité - Universitätsmedizin Berlin
ROR ID: https://ror.org/001w7jn25
Which part of the record needs to be changed? Primary name
Description of change: Name of institution remains always in German. Affiliation Guidelines: https://bibliothek.charite.de/fileadmin/user_upload/microsites/sonstige/bibliothek/Downloads/Affiliation_guideline_of_Charit%C3%A9_-_Universita%CC%88tsmedizin_Berlin_2021-02-22.pdf 
Other information about this request: The name of the Charité should not be translated into English. If special characters are not possible then it may be shown thus: Charite - Universitatsmedizin Berlin

MG Note:
Change name: Charité - Universitätsmedizin Berlin
Delete label: Charité - Universitätsmedizin Berlin

Update: change.name==Charité - Universitätsmedizin Berlin; delete.labels==Charité - Universitätsmedizin Berlin;

**Comment by KellyStathis** [comment]
I agree we should make this change as indicated. The ROR metadata policies states that "The primary name field defaults to English when an English version of an organization’s name is available." In this case, an English version of the name is not available since the organization's guidelines specify that it should not be translated.

Would we move the English translated name to the alias field, or remove it entirely?

**Comment by arthurpsmith** [comment]
Yes, I don't think this one needs a second review :) Moving to ready for sign-off!

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
