### ISSUE TITLE
Add a new organization to ROR: 
 
ajps publications 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#267]
Summary of request: Add a new organization to ROR

Name of organization: ajps publications 
Website: https://www.ajpsdz.org/
Link to publications: https://doi.org/10.35788/ajps
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: ajps publications
Acronym/abbreviation: ajps
Related organizations: 
City: skikda
Country: algeria
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
I removed the "Crossref Funder ID" as that was not a Crossref Funder ID, just a copy of the publication DOI. They appear to be a small publisher with one journal "African Journal of Political Sciences" from Algeria which seems to publish in Arabic? Not to be confused with "African Journal of Political Science" from South Africa which publishes in English and French. Their website is a mess - at least when I opened it with Chrome most of the pages were blank or almost full of advertising. The journal pages also had ads but they appear to be legitimate political science research papers. They've been around since 2012, or at least that is when the first issue of the journal came out.

So this is a scope question - are we adding small publishers like this one, or not? I'd be inclined to say no. Willing to hear a second opinion though.

**Comment by carlyrobinson** [comment]
I couldn't find a link from the ajps website (https://www.ajpsdz.org/) to publications (https://doi.org/10.35788/ajps). Many of their webpages didn't contain content and their About page seem to have formatting errors so that it wasn't readable. The African Journal of Political Sciences is supposed to be OA, but I could access full-text to any of the articles in the publication. There was just metadata and a download button that I was a bit worried about. 

I'm not sure that it makes sense to assign a ROR at this point.

**Comment by adambuttrick** [comment]
Situation is unchanged, so I'm going to go ahead and decline.
