### ISSUE TITLE
Add a new organization to ROR: 
 
Canadian Centre for Electron Microscopy

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#274]
Summary of request: Add a new organization to ROR

Name of organization: Canadian Centre for Electron Microscopy
Website: https://ccem.mcmaster.ca/
Link to publications: https://doi.org/10.1016/j.gca.2020.11.007, https://doi.org/10.1016/j.chemgeo.2018.07.031
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: none
Acronym/abbreviation: CCEM
Related organizations: McMaster University https://ror.org/02fa3aq29 (related)
City: Hamilton, ON
Country: Canada
Year established: 2004
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility
Other information about this request: We are a core research facility located at McMaster University, but have our own affiliation for publications and tracking of publications that come from our facility. We would like a ROR set up for CCEM so we can easily track publications from our Centre and make it easier for our users to cite us in publications.

**Comment by arthurpsmith** [comment]
I searched through wikimedia, ISNI and Crossref and they indeed seem not to be listed in any of those. Website is under the university's domain; affiliations of staff in publications also always seem to include the university as well. Searching Google scholar I could not find any cases of acknowledgement of the facility that didn't also include a staff member as one of the co-authors. So I think this does not meet our criteria for an independent top-level research organization.

**Comment by KellyStathis** [comment]
CCEM is one of 17 national research facilities in Canada funded through Major Science Initiatives (MSI): https://web.archive.org/web/20210418061806/https://www.innovation.ca/national-research-facilities

Although these facilities may be hosted at a university, they function more autonomously from the university than a typical department. Other examples in ROR include Ocean Networks Canada (https://ror.org/05gknh003), hosted at the University of Victoria, and Canadian Light Source (https://ror.org/001bvc968), at the University of Saskatchewan. 

Since this facility is considered national, I think it is sufficiently independent from McMaster and meets our criteria for inclusion in ROR. Moving to "Needs discussion".

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02w3v2f07 in release v1.0.
