### ISSUE TITLE
Add a new organization to ROR: NCCR Catalysis

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2877]
Summary of request: Add a new organization to ROR

Name of organization: NCCR Catalysis*en
Website: https://www.nccr-catalysis.ch
Domains: nccr-catalysis.ch
Link to publications: https://doi.org/10.1016/j.jcat.2022.02.014; https://doi.org/10.1038/s41467-022-28536-w; https://doi.org/10.1039/d1sc00482d; https://doi.org/10.1002/wcms.1604
Organization type: Facility; Funder
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0005 1092 057X
GRID ID:
Crossref Funder ID: 501100023650
Other names for the organization: 
Aliases: National Centre of Competence in Research Catalysis*en; National Center of Competence in Research Catalysis*en
Labels: 
Acronym/abbreviation:
Related organizations: https://ror.org/05a28rw58 (related) https://ror.org/02s376052 (related) https://ror.org/00yjd3n13 (parent)
City: Zürich
Country: Switzerland
Geonames ID: 2657896
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by arthurpsmith** [comment]
@adambuttrick I'm wondering why this hasn't been tackled yet? We seem to have several of these NCCR's in ROR already: https://ror.org/03xf64p49 (NCCR DFAB), https://ror.org/033f9yy33 (NCCR Chemical Biology), https://ror.org/00ghka958 (NCCR Evolving Language). This one is definitely used as an affiliation, and it's not a single-parent organization.
However I can see a possible issue in that these are short-term funding initiatives rather than ongoing organizations. From the Swiss NSF page here: https://www.snf.ch/en/FJBJ8XGQ1tjG8J8w/funding/programmes/national-centres-of-competence-in-research-nccr - there are a large number of "Concluded NCCRs". However as minimum 8-year-funded efforts maybe we should consider them long-term enough to have ROR ids? I'm not sure on what our policy should be - maybe this should be a discussion topic at some point?
