### ISSUE TITLE
Modify the information in an existing ROR record: 
Molecular Devices (United Kingdom) https://ror.org/03y8xh662


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#318]
Summary of request: Modify the information in an existing ROR record

Name of organization: Molecular Devices (United Kingdom)
ROR ID: https://ror.org/03y8xh662
Which part of the record needs to be changed? Something else
Description of change: Molecular Devices' website reports its country / address as Molecular Devices, LLC., 3860 N First Street, San Jose, CA 95134, so USA

**Comment by arthurpsmith** [comment]
GRID created this record for the UK subsidiary, but there's no record for the US parent. I think we should create a separate ROR record for the parent organization (and link them with our parent/child relationship). The ISNI and Wikipedia page on this record should be moved to the US parent. However the Wikidata ID for the US parent is different: Q6895942.

**Comment by KellyStathis** [comment]
I agree with Arthur's assessment - this ROR ID should stay with the UK subsidiary, and we should create a new ROR record for the US parent.

I noticed this ROR ID is linked to the UK Wikidata ID - https://www.wikidata.org/wiki/Q30290687 - but not the US one. This supports us keeping this ROR for the UK subsidiary, rather than updating it to represent the US parent.

**Comment by adambuttrick** [comment]
Created and approved record for parent organization with #452 . Moving this to declined, as we're leaving the existing ROR record as is.
