### ISSUE TITLE
Modify the information in an existing ROR record: 
Stiftelsen Riksbankens Jubileumsfond https://ror.org/02jkbm893


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#324]
Summary of request: Modify the information in an existing ROR record

Name of organization: Stiftelsen Riksbankens Jubileumsfond
ROR ID: https://ror.org/02jkbm893
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: The foundation is listed under its former English name: Bank of Sweden Tercentenary Foundation. I would be grateful if you could change it to the correct version: Stiftelsen Riksbankens Jubileumsfond and also change the wording underneath to For the advancement of the Humanities and Social sciences.

Update: change.name==Stiftelsen Riksbankens Jubileumsfond; replace.labels==Bank of Sweden Tercentenary Foundation*English; add.acronyms==RJ;

**Comment by arthurpsmith** [comment]
Going by their English "about" page - https://www.rj.se/en/about-rj2/ the English name they use is "Riksbankens Jubileumsfond", with abbreviation "RJ". The Swedish name we have seems what they use on the Swedish version of that page ("Stiftelsen Riksbankens Jubileumsfond"). Their request regarding "For the advancement of the Humanities and Social sciences" seems confused - unless they consider it part of a full official name (for example we could add "Riksbankens Jubileumsfond For the advancement of the Humanities and Social sciences" as an alternate label I guess) I don't think we have a place for logo text like that in ROR.

So I recommend replacing the primary label with their English label "Riksbankens Jubileumsfond", retaining the Swedish label, adding "RJ' as an acronym, and keeping the former primary label as another alternate label.

**Comment by KellyStathis** [comment]
I'm not sure about removing the word "Stiftelsen" because it doesn't appear on the English version on the website. Arguments for including it:

- From what I can tell, "Stiftelsen" (which means "foundation") is part of their official Swedish name - they may have just thought it was awkward or redundant to translate on the English side? I wouldn't attribute too much significance to that omission. I'm not seeing evidence that "Riksbankens Jubileumsfond" an official "English" name - particularly because it's still Swedish! I think it's just a short name.
- The word "Foundation" is already part of their current English translated name in ROR.
- There are other Swedish foundations in ROR that keep the word "Stiftelsen": https://ror.org/search?query=stiftelsen

My proposal:
- primary name: use the full name, "Stiftelsen Riksbankens Jubileumsfond"
- alias/label: "Riksbankens Jubileumsfond" - if added as a label, I would say it is Swedish for language, not English
- label: "Bank of Sweden Tercentenary Foundation" (English)
- acronyms: "RJ"

For the request on "For the advancement of the Humanities and Social sciences", I think they might be referring to the alias we have, "The Swedish Foundation for Humanities and Social Sciences" - we are missing the word "Advancement". Not sure if we should update this alias or remove it, if we don't normally include taglines like this?

Moving to "Needs discussion."

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
