### ISSUE TITLE
Add a new organization to ROR: 
 
CACAO

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#348]
Summary of request: Add a new organization to ROR

Name of organization: CACAO
Website: https://gowiki.tamu.edu/
Link to publications: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009463; . http://www.ableweb.org/volumes/vol-39/?art=6
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Community Assessment of Community Annotation with Ontology
Acronym/abbreviation: CACAO
Related organizations: https://ror.org/01f5ytq51
City: College Station
Country: United States
Year established: 2011
How will a ROR ID for this organization be used? To identify affiliations for datasets
Other information about this request:

**Comment by nlundvick** [comment]
This is a community that hosts annual competitions for undergraduate students to create gene annotations, ran by Texas A&M. Related publications use Texas A&M affiliation. Website is a wiki page within Texas A&M .edu domain. Request is to add ROR for affiliations in datasets, but university affiliations may be more appropriate. Determination: Not in scope. Moving to Second Review for additional reviewer comments.

**Comment by arthurpsmith** [comment]
I agree with @nlundvick - this is a competition, not an organization, and it seems to be heavily associated with Texas A&M. I searched Google Scholar for  references to the full name ("Community Assessment of Community Annotation with Ontology") and it is referenced or acknowledged in about a dozen articles, but not used as an affiliation. Searching for the abbreviation CACAO brought up entirely unrelated papers so that wasn't helpful.  Anyway, I don't see this as being in scope for ROR.
