### ISSUE TITLE
Add a new organization to ROR: The MuseumFactory

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#352]
Summary of request: Add a new organization to ROR

Name of organization: The MuseumFactory
Website: https://demuseumfabriek.nl
Link to publications: 
Organization type: Archive
Wikipedia page: https://en.wikipedia.org/wiki/De_Museumfabriek
Wikidata ID: https://www.wikidata.org/wiki/Q2203052
ISNI ID: https://isni.org/isni/0000000417847312
GRID ID:
Crossref Funder ID:
Other names for the organization: De MuseumFabriek
Acronym/abbreviation: DMF
Related organizations: 
City: Enschede
Country: Netherlands
Geonames ID: 2756071
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by arthurpsmith** [comment]
I added wikipedia/wikidata/ISNI id's.

This appears to be a relatively new museum in the Netherlands, and has gone  through several names - the English wikipedia page mentions "Jannink Museum of Textiles and Social Life"  and "TwentseWelle" as previous names. From their website they appear to be closely related to (share governance with) "Rijksmuseum Twenthe", a much more well-established museum in the same city, which also does not seem to be in ROR.

"Rijksmuseum Twenthe" seems to be well-referenced in research literature, though not as an affiliation.  I couldn't find any references to "De MuseumFabriek", or  "The MuseumFactory", perhaps because those  names are relatively new. I  did find  some "TwentseWelle" references (but again not as affiliations).

This seems to be a borderline case to me. Perhaps we should put it on hold for now, given the newness of the name. If we do add a ROR id for this we should definitely also add one for "Rijksmuseum Twenthe", with which it is related.

**Comment by nlundvick** [comment]
Concur with @arthurpsmith - due to newness of this organization, place request on hold. If adding a ROR ID for The MuseumFactory, also add for one for Rijksmuseum Twenthe (https://www.rijksmuseumtwenthe.nl/)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03srysw20 in release v1.1.
