### ISSUE TITLE
Modify the information in an existing ROR record: 
VU Amsterdam https://ror.org/008xxew50


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#359]
Summary of request: Modify the information in an existing ROR record

Name of organization: VU Amsterdam
ROR ID: https://ror.org/008xxew50
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: change primary name: Vrije Universiteit Amsterdam
(The official primary name of our university is Vrije Universiteit Amsterdam, even in English texts.   please change “VU Amsterdam” everywhere in “Vrije Universiteit Amsterdam”? Additionally you can add “VU Amsterdam” to the aliases.)

change homepage URL: https://vu.nl

add RingGoldID: 1190

Update: change.name==Vrije Universiteit Amsterdam; delete.labels==Vrije Universiteit Amsterdam; add.aliases==VU Amsterdam; replace.links==https://vu.nl;

**Comment by arthurpsmith** [comment]
Recommended change seems fine. The www-prefixed website we have now redirects to the one without the www so let's follow that as well. So we should move the current Dutch (NL) label to the primary label, move the current primary label to an alternate, and shorten the website URL as requested.
I can't confirm the Ringgold ID except that Wikidata also has 1190 so that seems fine too (if we include these at all).

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
