### ISSUE TITLE
Add a new organization to ROR: 
 
Institut Terre et Environnement de Strasbourg

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#365]
Summary of request: Add a new organization to ROR

Name of organization: Earth and Environment Institute of Strasbourg
Website: https://ites.unistra.fr
Link to publications: https://dx.doi.org/10.1038/s41529-021-00196-z
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: ITES
Labels: Institut Terre et Environnement de Strasbourg*French
Related organizations:  https://ror.org/00pg6eq24 (parent) https://ror.org/02feahw73 (parent) https://ror.org/02jhjzd11 (parent)
City: Strasbourg
Country: France
Geonames ID: 2973783
Year established: 2021
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility
Other information about this request:

**Comment by arthurpsmith** [comment]
This is a new institute located at University of Strasburg - https://ror.org/00pg6eq24 - (also the website is under the unistra.fr domain, and the affiliations in the example provided list both the institute and U. Strasburg as affiliation). However, it is also a CNRS -funded institute. Given the way we've handled similar institutes at other French universities this probably should have its own ROR id, but it might be something we should wait a bit on, or defer since so far it doesn't seem to be independent of the university.

**Comment by KellyStathis** [comment]
We may need to have a consistent approach to CNRS funded institutes, including UMRs. My understanding is that they not independent of universities, but they can be cross-institutional collaborations. They can also be time-limited since funding is renewable, not ongoing. Looking at the Advanced Search at https://annuaire.cnrs.fr/NavigationServlet there are over 1,400 with Country=France.

Does anyone on the curation advisory board have more context for how these are structured? I found https://www.cnrs.fr/fr/cnrsinfo/le-cnrs-simplifie-ses-structures-de-recherche but I am still fuzzy on the details.

Moving to "Needs discussion" :)

**Comment by mariagould** [comment]
I agree with Kelly on taking a bigger-picture look in the future at all of the CNRS-related records. 

For the present case, it looks like the institute formed recently as a merger between the Institute of Earth Physics of Strasbourg and the Laboratory of Hydrology and Geochemistry of Strasbourg (see https://ites.unistra.fr/linstitut/historique-anciennes-umrs). The second entity has a ROR ID: https://ror.org/03y81da23. 

Given the number of publications already associated with the institute, and its unique position with having multiple parents (Univ of Strasbourg, CNRS, and ENGEES), and its position as a merged entity of the prior two organizations, I think it would make sense to create a new ROR ID for Institut Terre et Environnement de Strasbourg. 

I will file a separate issue for redirecting https://ror.org/03y81da23 to the new ROR ID when we have redirecting functionality in place.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0530qwm02 in release v1.0.
