### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute for the Study of Labor https://ror.org/029s44460


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#375]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute for the Study of Labor
ROR ID: https://ror.org/029s44460
Which part of the record needs to be changed? Primary name
Description of change: IZA's own website https://www.iza.org gives their English name as 'IZA - Institute of Labor Economics' (or just 'IZA') and their German name as 'Forschungsinstitut zur
Zukunft der Arbeit GmbH (IZA)'

Changes approved by curators:

- Change primary name to "IZA Institute of Labor Economics"
- Add "Institute for the Study of Labor" as an alias.

Update: change.name==IZA - Institute of Labor Economics; add.aliases==Institute for the Study of Labor; replace.labels==Forschungsinstitut zur Zukunft der Arbeit GmbH (IZA)*German;

**Comment by arthurpsmith** [comment]
We definitely need to fix the main label here. Looking through Google Scholar, the acronym IZA has been used as part of this affiliation for many years - here's one from 1999: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=165870
where it is phrased as "IZA Institute of Labor Economics". The request here includes a '-' character, but I don't actually see that anywhere on the iza.org website, it is always (in English) referred to either as IZA, or in the header format with a large IZA followed directly by "Institute of Labor Economics".

As to the German name, the website header in German is the same as in English, with the English version of the name. So that should definitely be our primary label here. We already have the same German name as in this request except without the "GmbH" or parenthetical IZA piece; generally we don't add GmbH's to our German labels, and IZA is there as an acronym so I think we should leave the German version of the name alone.

So the only change I think should be made here is to the primary (English) label which I believe should be:
"IZA Institute of Labor Economics"

**Comment by KellyStathis** [comment]
I agree with Arthur's assessment. My only question is whether we should add "Institute for the Study of Labor" as an alias - I don't see this on their official website, but that comes up as an alternate name for IZA from a few other sources ([Wikidata page](https://www.wikidata.org/wiki/Q317269), [DDI Alliance](https://ddialliance.org/project/institute-for-the-study-of-labor-iza-international-data-service-center-idsc). I wonder if it is an alternate translation of the German that has stuck?

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
