### ISSUE TITLE
Add a new organization to ROR: 
 
Hakai Institute

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#376]
Summary of request: Add a new organization to ROR
Name of organization: Hakai Institute
Website: www.hakai.org
Link to publications: https://doi.org/10.21966/1.566666
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://en.wikipedia.org/wiki/Hakai_Institute
Wikidata ID: https://www.wikidata.org/wiki/Q5640294
ISNI ID: https://isni.org/isni/0000000492257240
GRID ID: 
Crossref Funder ID: 
Other names for the organization: N/A
Acronym/abbreviation: Hakai
Related organizations: Tula Foundation https://ror.org/0029jxk29 (parent) funds the Hakai Institute
City: Campbell River, British Columbia
Country: Canada
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by arthurpsmith** [comment]
They definitely have research publications where this is used as an affiliation - the linked publication seems to be a dataset; another example as a regular article is https://doi.org/10.1002/ece3.7022 . The one question I have is the degree of separation between this and the Tula Foundation for which we already have a ROR id (and which is acknowledged as a research funder in itself). Tula seems to be their only source of funds and so is in a sense a top-level organization for Hakai - however when used as an affiliation, Tula doesn't seem to be mentioned, and the website is independent. So I lean towards creating a separate ROR id for Hakai Institute, but I'm not completely certain on this.

**Comment by Br-Johnson** [comment]
The Tula Foundation funds several projects, one of which is The Hakai Institute. Most staff scientists and research technicians would say they work for the Hakai Institute rather than the Tula Foundation. The Hakai Institute is more recognizable as an organization based on the work we publish as opposed to the Tula Foundation. 

Currently, there is no way to affiliate our work with the Hakai Institute in DataCite Metadata Schema for example. We've been using Tula as our affiliation there, but as you'll see most researchers note their affiliation in research papers to the Hakai Institute and then acknowledge the Tula Foundation as the funder.

It is a slightly odd scenario I gather, but I spoke with our President Dr. Eric Peterson on this matter specifically and he is OK with using Hakai as our Research Organization and Tula as the funder as this logically represents how the two organizations are related.

Hope this helps! Happy to provide more context if necessary.

**Comment by KellyStathis** [comment]
Thanks @Br-Johnson for this added context! I'm familiar with Hakai and this reasoning makes sense to me.

**Comment by KellyStathis** [comment]
Some additional metadata - the Hakai Institute has a Crossref Funder ID: http://dx.doi.org/10.13039/100016884. Note that Crossref references the Tula Foundation as a "broader" organization; I think we should mirror this in ROR, with the Tula Foundation as the parent org.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02pry0c91 in release v1.0.
