### ISSUE TITLE
Add a new organization to ROR: 
 
Fundación Centro de Estudios Andaluces

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#377]
Summary of request: Add a new organization to ROR

Name of organization: Fundación Centro de Estudios Andaluces
Website: https://www.centrodeestudiosandaluces.es/
Link to publications: We are in the process of registering with CrossRef in order to assign DOIs to our past and new publications.
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://es.wikipedia.org/wiki/Centro_de_Estudios_Andaluces
Wikidata ID: https://www.wikidata.org/wiki/Q5761665
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Fundación Centra
Acronym/abbreviation: Centro de Estudios Andaluces
Related organizations: 
City: Seville
Country: Spain
Year established: 2001
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders
Other information about this request:

**Comment by KellyStathis** [comment]
This appears to be an organization that supports research about Andalusia. It is not already in ROR. It is in scope for ROR because it:

- is an established organization
- is a top-level organization and not a subsidiary unit
- is associated with research publications and/or other activities:
  - they publish the journal Andalucia en la Historía (see https://www.centrodeestudiosandaluces.es/publicaciones/cat/revista-andalucia-en-la-historia, https://portal.issn.org/resource/ISSN/1695-1956)
  - they fund research projects: https://www.centrodeestudiosandaluces.es/convocatoria-de-proyectos

They are associated with the Consejería de la Presidencia, Administración Pública e Interior (ROR: https://ror.org/05pmk8j16) but appear to be a related organization with separate governance.

Additional metadata:
ISNI: https://isni.org/isni/000000012097322X

**Comment by arthurpsmith** [comment]
I found another ISNI for this organization - https://isni.org/isni/0000000120980411 - looks like maybe ISNI has two records for this?
Anyway, yes it does appear well-established and engaged in research, it should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05v01tw04 in release v1.0.
