### ISSUE TITLE
Modify the information in an existing ROR record: 
Institut de Physique du Globe de Paris https://ror.org/004gzqz66


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#391]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institut de Physique du Globe de Paris
ROR ID: https://ror.org/004gzqz66
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: The primary name is lowercase (except Paris) "Institut de physique du globe de Paris". 

The English name is "Paris institute of earth physics"

Website: https://www.ipgp.fr

Update: change.name==Institut de physique du globe de Paris; replace.labels==Paris Institute of Earth Physics*English; replace.links==https://www.ipgp.fr/; delete.aliases==Paris Institute of Earth Physics;

**Comment by arthurpsmith** [comment]
To confirm this capitalization request is how it is displayed by the organization itself, see this page: http://www.ipgp.jussieu.fr/en/governance
But for example in affiliations the other words do seem to typically be capitalized - for example the affiliations in this article: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2012GL052387
Anyway, as the organization has requested the capitalization change I think we should accept it.

On the English name, I can't find "Paris Institute of Earth Physics" or the lower-case version they request anywhere on their website. Wikidata does use "Paris Institute of Earth Physics" as the English label though. This does seem a better translation of the name than the current one we have, so since they requested it I'm fine with making that change.

As to the website - both our current url and the one they request work and provide exactly the same set of web pages, and both on their contact page suggest 'ipgp.fr' is the correct domain now, so I agree we should switch to the shorter URL for the website.

So, recommended changes are:
* primary label should be "Institut de physique du globe de Paris"
* English label should be "Paris Institute of Earth Physics"
* Website should be https://www.ipgp.fr

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
