### ISSUE TITLE
Add a new organization to ROR: 
 
Gothenburg Botanic Garden

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#392]
Summary of request: Add a new organization to ROR

Name of organization: Gothenburg Botanic Garden
Website: https://www.botaniska.se/
Link to publications: https://doi.org/10.7717/peerj.11185
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://en.wikipedia.org/wiki/Gothenburg_Botanical_Garden
Wikidata ID: https://www.wikidata.org/wiki/Q956772
ISNI ID: https://isni.org/isni/0000000110124355
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Göteborgs Botaniska Trädgård
Acronym/abbreviation: GBG
Related organizations: https://ror.org/00a4x6777 (parent)
City: Gothenburg
Country: Sweden
Year established: 1923
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility
Other information about this request: this is a facility in the DiSSCo research infrastructure

**Comment by KellyStathis** [comment]
This is a botanical garden involved in research: https://www.botaniska.se/samlingar-forskning/forskningsteman/. It is not already in ROR. It is in scope for ROR because:
- it is used as an affiliation, for example: https://www.mdpi.com/2223-7747/10/3/580
- there are also other botanical gardens in ROR: https://ror.org/search?query=botanical+garden
- it is an established organization (1923)

The garden's email addresses are @vgregion.se, but I wasn't able to find a reference to the Gothenburg Botanic Garden on the parent organization's website (https://www.vgregion.se/). I think they are sufficiently independent.

**Comment by arthurpsmith** [comment]
I don't think we have a ROR for vgregion.se anyway. Yes, this should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/035tz7392 in release v1.0.
