### ISSUE TITLE
Add a new organization to ROR: 
 
Suzhou institute of North China Electric Power University

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#394]
Summary of request: Add a new organization to ROR

Name of organization: Suzhou Institute of North China Electric Power University
Website: https://szyjy.ncepu.edu.cn
Link to publications: https://english.ncepu.edu.cn/hddt/31048.html
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Labels: 华北电力大学苏州研究院*Chinese
Acronym/abbreviation: SZYJY
Related organizations: https://ror.org/04qr5t414 (parent)
City: Suzhou
Country: China
Geonames ID: 1886760
Year established: 2012
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility
Other information about this request: This institute was established in China in April 2021 - I had trouble finding URL for publications.

**Comment by adambuttrick** [comment]
Can find no instances of affiliation usage. Publication provided is an announcement from the org's website describing the opening of the facility, seemingly as part of North China Electric Power University. Would need something else further to establish its independence. Otherwise, appears out of scope.

**Comment by arthurpsmith** [comment]
Hmm, when I search the exact proposed name on Google Scholar I get a lot of hits:
https://scholar.google.com/scholar?start=30&q=%22Suzhou+institute+of+North+China+Electric+Power+University%22&hl=en&as_sdt=0,33
However they all appear to be publications in Chinese journals, which can be downloaded only from CNKI (and I don't have access)?
I think this is a major research institute, well-established (since at least 2012, I don't know where the 2021 date came from in the input data) and it is physically separate from the main university. On the other hand their website domain is a subdomain of the main university site, and there's no sign they have another "parent" organization besides the university. So if we were including non-top-level institutes then I think this should definitely be in ROR; as it is it probably is out of scope. But maybe needs further discussion? If we had somebody more familiar with Chinese organizations that might help here!

**Comment by adambuttrick** [comment]
Fixed the date, since this was appears to have been a typo in the request. 

@arthurpsmith After subtracting out the CNKI articles that were polluting the Google Scholar results, I was able to find "Suzhou institute of North China Electric Power University" as an affiliation in IEEE (https://ieeexplore.ieee.org/document/6330107 ; https://ieeexplore.ieee.org/document/6896157 ; https://ieeexplore.ieee.org/document/6330107), with the only caveat being that the author's profiles use the university affiliation, not the institute (e.g., https://ieeexplore.ieee.org/author/37304066300 ; https://ieeexplore.ieee.org/author/37405735500 ; https://ieeexplore.ieee.org/author/38543674000).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02g5psh91 in release v1.3.
