### ISSUE TITLE
Add a new organization to ROR: 
 
Trout Lake Station

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#402]
Summary of request: Add a new organization to ROR

Name of organization: Trout Lake Station
Website: https://limnology.wisc.edu/trout-lake-station-welcome/
Link to publications: e.g. see Google scholar profile of Tim Kratz: https://scholar-google-com.ezproxy.library.wisc.edu/citations?user=eB_hInEAAAAJ&hl=en&oi=sra
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000404519715
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Trout Lake Research Station, UW Trout Lake Station
Acronym/abbreviation: TLS
Related organizations: University of Wisconsin Madison (parent), UW Center for Limnology (academic unit)
City: Boulder Junction
Country: United States
Year established: 1925
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: Trout Lake Station is a core research facility of UW Madison but is located off the main campus in Boulder Junction, WI. It hosts users from >30 academic, agency and other units each year to conduct research and is the northern site for the NTL_LTER whose data is referenced and used by researchers for global comparative analyses of lakes.

**Comment by adambuttrick** [comment]
Not certain whether this sufficiently constitutes a top-level entity as it is under the Center for Limnology at the University of Wisconsin-Madison. It's director appears to use the University of Wisconsin affiliation, (https://scholar.google.com/citations?user=-0lQw-wAAAAJ). Other research station entities in ROR have a greater degree of independence.

**Comment by arthurpsmith** [comment]
I agree this is not a top-level research organization. At some point we should find a way to support these, but right now out of scope for ROR.

The ISNI entry they reference is also interesting, as it has "University of Wisconsin Madison Center for Limnology" as one of the names - but the request lists that as a parent. So things are a bit mixed up with respect to ISNI on this one anyway. On the Long-Term Ecological Research issue, we have at least one other request on this (#197, see also #442) so that would be a separate consideration.

Anyway, marking as declined and out of scope now.
