### ISSUE TITLE
Add a new organization to ROR: 
 
Human Rights Care - HRC

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#403]
Summary of request: Add a new organization to ROR

Name of organization: Human Rights Care - HRC
Website: www.humanrights.care
Link to publications: www.humanrights.care
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: هيومن رايتس كير 
Acronym/abbreviation: HRC
Related organizations: 
City: Hurghada
Country: Egypt
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by adambuttrick** [comment]
The organization describes itself as "a non-governmental organization dedicated to the defense of human rights, by identifying violations and collecting data on human rights violations and dissemination and dissemination, promoting public awareness and pressure on the responsible authorities to stop these violations." In order to be added, I think we would need examples of these data outputs, as I could find nothing on the organization's site nor reference to these datasets.

**Comment by arthurpsmith** [comment]
I can't find either the English or Arabic name used as an affiliation on publications (via Google Scholar). This is a relatively new organization (established 2020) so perhaps there just hasn't been time for that, but looking at their website I don't think this is likely to be a research organization that's within our usual scope. I'm going to move this to "on hold" for now but if somebody else agrees it's unlikely to ever be associated with research outputs I'm ok with declining as out of scope.

**Comment by adambuttrick** [comment]
Research outputs have not been produced, so declining as out of scope.
