### ISSUE TITLE
Modify the information in an existing ROR record: 
Universidad Nacional de Colombia https://ror.org/059yx9a68


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#407]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universidad Nacional de Colombia
ROR ID: https://ror.org/059yx9a68
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Other IDs for the organization
Description of change: The primary name must be changed to "Universidad Nacional de Colombia" according to the provisions of  Resolution 712 of 2015 of the Rectory of the Universidad Nacional de Colombia http://www.legal.unal.edu.co/rlunal/home/doc.jsp?d_i=81511 which states the university name shouldn't be translated. Also ISNI record could be changed to https://isni.org/isni/0000000491290751 which is more acurate and global than the current ISNI in ROR

Update: change.name==Universidad Nacional de Colombia; delete.labels==Universidad Nacional de Colombia; replace.ISNI==0000 0004 9129 0751;

**Comment by adambuttrick** [comment]
Translation of the relevant section from the linked document:

"1. The institution must be referenced in all cases, regardless of the language, in Spanish, as follows: "Universidad Nacional de Colombia"

We would need a policy change on primary names being in English in order to  update accordingly, but the request is otherwise well supported.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
