### ISSUE TITLE
Add a new organization to ROR: 
 
Instituto Interdisciplinario de Economía Política de Buenos Aires

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#434]
Summary of request: Add a new organization to ROR

Name of organization: Buenos Aires Interdisciplinary Political Economy Institute
Website: https://iiep-baires.econ.uba.ar
Link to publications: https://ideas.repec.org/p/ake/iiepdt/201944.html
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Buenos Aires Interdisciplinary Political Economy Institute; IIEP; 
Acronym/abbreviation: IIEP (UBA CONICET)
Labels: Instituto Interdisciplinario de Economía Política de Buenos Aires (Spanish)
Aliases: IIEP Baires
Related organizations: Universidad de Buenos Aires https://ror.org/0081fs513 (parent); Consejo Nacional de Investigaciones Científicas y Técnicas https://ror.org/03cqe8w59 (parent)
City: Buenos Aires
Country: Argentina
Geonames ID: 3435910
Year established: 2011
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
This appears to be a joint venture between the University of Buenos Aires and Argentina's National Council of Scientific and Technical Research that sponsors and conducts economic research in Argentina. It is not already in ROR. It is in scope for ROR because it:

-         is an established organization
-         is a top-level organization and not a subsidiary unit
-         is associated with research publications and/or other activities, as evident by the linked affiliation usage: https://scholar.google.com/citations?user=jhV31aQAAAAJ 
https://scholar.google.com/citations?user=g2gkd7sAAAAJ
https://scholar.google.com/citations?user=SwF0pBIAAAAJ
https://www.fund.ar/wp-content/uploads/2021/09/El-Potencial-Productivo-Verde-de-la-Argentina.pdf
- 
- Similar records in ROR: https://ror.org/02pfge856 https://ror.org/00avq9860 https://ror.org/014z5x149
-

**Comment by arthurpsmith** [comment]
Yes I agree. I wonder if we should do a bit more to systematically add joint institutes of this sort that are located at the University of Buenos Aires? Anyway, this one surely qualifies.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/019ptgs60 in release v1.0.
