### ISSUE TITLE
Add a new organization to ROR: 
 
AIR Institute

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#436]
Summary of request: Add a new organization to ROR

Name of organization: AIR Institute
Website: https://air-institute.org/
Link to publications: 10.3390/s21010236
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Fundación Instituto Internacional de Investigación en Inteligencia Artificial y Ciencias de la Computación
Acronym/abbreviation: AIR
Labels: Fundación Instituto Internacional de Investigación en Inteligencia Artificial y Ciencias de la Computación (Spanish)
Related organizations: University of Salamanca https://ror.org/02f40zc51 (related), Junta de Castilla y León https://ror.org/02s8dab97 (related), University of Valladolid https://ror.org/01fvbaw18 (related)
City: Valladolid
Country: Spain
Geonames ID: 3106672
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by adambuttrick** [comment]
This appears to be a private research organization focused on machine learning and related topics. It is not already in ROR. It is in scope for ROR because it:

is an established organization
is a top-level organization and not a subsidiary unit
is associated with research publications and/or other activities

https://orcid.org/0000-0002-7768-3124
https://orcid.org/0000-0002-3444-4393
https://orcid.org/0000-0003-4734-5068
https://ideas.repec.org/a/gam/jsusta/v13y2021i16p8952-d611814.html
https://www.econstor.eu/bitstream/10419/241573/1/1744671109.pdf


Similar records in ROR: https://ror.org/03x89f523 https://ror.org/034dfmd43

**Comment by arthurpsmith** [comment]
Hi - agreed this should have a ROR. However, is it not the same as https://ror.org/03c0ach84 ? Hmm, I guess it is in a different location within Spain, but they both seem to go by "Artificial Intelligence Research Institute" or some version of that. The other one is clearly part of CSIC and this one makes no mention. Also associated with different universities (Barcelona vs Valladolid).

Ok, yes I think this should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00g3fjr10 in release v1.0.
