### ISSUE TITLE
Add a new organization to ROR: 
 
Centro Nacional de Investigaciones de Café (Cenicafé)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#439]
Summary of request: Add a new organization to ROR

Name of organization: Centro Nacional de Investigaciones de Café - Cenicafé
Website: https://www.cenicafe.org/
Link to publications: https://publicaciones.cenicafe.org/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://fr.wikipedia.org/wiki/Centro_Nacional_de_Investigaciones_de_Café
Wikidata ID: Q21511954
ISNI ID: https://isni.org/isni/0000000122942697
GRID ID: 
Crossref Funder ID: http://dx.doi.org/10.13039/100019597
Other names for the organization: National Coffee Research Center (Cenicafé)
Aliases:
Labels: National Coffee Research Center - Cenicafé*English
Acronym/abbreviation: Cenicafé
Related organizations: Colombian Coffee Growers Federation (FNC)
City: Manizales Colombia
Country: Colombia
Geonames ID: 3675443
Year established: 1938
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: This institution is part of the great family of the Colombian Coffee Growers Federation (FNC). Since its creation it has led technological advances in coffee, research and appropriate, competitive and sustainable knowledge to improve coffee production and thus contribute to Colombian coffee growers’ well-being.

The Cenicafé team is made up of professionals with doctorates (PhD’s) and master’s degrees (MSc’s) in different scientific disciplines. Under the guidance of Cenicafé researchers, students from different Colombian universities work on their professional thesis, and special projects are executed with the participation of researchers from other institutions.

**Comment by adambuttrick** [comment]
This appears to be an organization that involved in conducting and publishing research related to the agriculture and production of coffee. It is not already in ROR. It is in scope for ROR because it:

- is an established organization
- is a top-level organization and not a subsidiary unit
- is associated with research publications and/or other activities:

research publications: https://publicaciones.cenicafe.org/index.php/avances_tecnicos/article/download/100/67 ; https://publicaciones.cenicafe.org/index.php/cenicafe/article/download/73/54

google_scholar_affiliation_usage: https://scholar.google.com/citations?user=-PEXZNIAAAAJ ; https://scholar.google.com/citations?user=2wYLttcAAAAJ ; https://scholar.google.com/citations?user=iR-1qA0AAAAJ

orcid_affiliation_usage: https://orcid.org/0000-0003-4861-9649 ; https://orcid.org/0000-0003-1576-2297 ; https://orcid.org/0000-0001-9433-6979 ; https://orcid.org/0000-0003-1967-0859 ; https://orcid.org/0000-0001-9690-1660 ; https://orcid.org/0000-0002-1639-1988 ; https://orcid.org/0000-0002-3536-0386 ; https://orcid.org/0000-0001-9875-9426 ; https://orcid.org/0000-0002-4446-9797 ; https://orcid.org/0000-0002-2029-8946 ; https://orcid.org/0000-0001-9465-3237 ; https://orcid.org/0000-0002-6031-3709 ; https://orcid.org/0000-0002-0946-9951


 Similar records in ROR: https://ror.org/02xq98350; https://ror.org/03d022g94

**Comment by arthurpsmith** [comment]
Agreed, definitely should be in ROR. I added the ISNI id. It also appears to have a Crossref funder ID but Crossref search hangs when I try to find it... not sure what's up with that.

**Comment by arthurpsmith** [comment]
Found the funder ID and added above.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03q60bw50 in release v1.0.
