### ISSUE TITLE
Upcoming merger of UNAVCO (https://ror.org/02n9tn974) and IRIS (https://ror.org/05xkn9s74): 
 


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#459]
Summary of request: Upcoming merger of UNAVCO (https://ror.org/02n9tn974) and IRIS (https://ror.org/05xkn9s74)

Name of organization: Earthscope Consortium
Website: 
Link to publications: 
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Our new organization will be called "EarthScope Consortium". Is there a way to plan ahead so that the new org has a ROR now, for our backend combined system development?

**Comment by adambuttrick** [comment]
Details of the merger are described here: https://sites.google.com/iris.edu/united/home 

It looks to still be somewhat early in its development, but because the institutions to be merged are long-standing and NSF-backed and they're looking to incorporate ROR as part of their infrastructure, perhaps we should approve? We would need the location of the future organization in order to create. We also don't have the ability to deprecate records at present, so that would have to be addresses down the road.
