### ISSUE TITLE
Add a new organization to ROR: 
 
Technological University of the Shannon: Midlands Midwest

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#470]
Summary of request: Add a new organization to ROR

Name of organization: Technological University of the Shannon: Midlands Midwest
Website: https://tus.ie/
Link to publications: https://doi.org/10.1108/HESWBL-03-2021-0058
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Technological_University_of_the_Shannon:_Midlands_Midwest
Wikidata ID: https://www.wikidata.org/wiki/Q106646552
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: TUS: Midlands Midwest, TUS: Midlands, TUS: Midwest
Acronyms: TUS
Labels: Ollscoil Teicneolaíochta na Sionainne: Lár Tíre Iarthar Láir*Irish
Acronym/abbreviation: TUS
Related organizations: https://ror.org/02dyxwz31 (related)
Limerick Institute of Technology
City: Athlone
Country: Ireland
Geonames ID: 3313472
Year established: 2021
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request: From Wikipedia: "The university was the result of a merger between two institutes of technology; the Athlone Institute of Technology and the Limerick Institute of Technology"

**Comment by adambuttrick** [comment]
Will create separate issue for the deprecation, but this otherwise looks appropriate for ROR. University conducting research with plenty of affiliation usage already, even though the merger occurred in October of last year.

Google Scholaraffiliation_usage: https://scholar.google.com/citations?user=SXKRLm0AAAAJ; https://scholar.google.com/citations?user=1URbOoYAAAAJ; https://scholar.google.com/citations?user=m93enKcAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0001-7720-7729 ; https://orcid.org/0000-0003-3656-3182 ; https://orcid.org/0000-0003-1443-9877 ; https://orcid.org/0000-0003-4247-0353 ; https://orcid.org/0000-0002-4472-4049 ; https://orcid.org/

**Comment by mariagould** [comment]
Agree with @adambuttrick that we should create a new entry in ROR for TUS and redirect the merged IDs to the TUS ID when we have redirecting functionality available.

**Comment by adambuttrick** [comment]
@tyoungmarsh #473 was declined as it was a duplicate request to merge the records. I responded to your message there with further details. The preexisting LIT & AIT RORs will remain as is until we have built the redirection and deprecation functionality into ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04efm0253 in release v1.0.
