### ISSUE TITLE
Add a new organization to ROR: 
 
Universidad Internacional de Ciencia y Tecnología - UNICyT

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#508]
Name of organization: Universidad Internacional de Ciencia y Tecnología - UNICyT
Website: https://www.unicyt.net
Link to publications: https://revistas.qlu.ac.pa/index.php/latitude/article/view/174, https://revistas.qlu.ac.pa/index.php/latitude/article/view/173, https://doi.org/10.46932/sfjdv2n4-020, https://revistas.usma.ac.pa/ojs/index.php/ipc/article/view/210/373, http://www.idi-unicyt.org/wp-content/uploads/2018/03/1701.03318.pdf, https://revistas.umecit.edu.pa/index.php/oratores/article/view/200
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: UNICyT
Related organizations: 
City: Panama City
Country: Panama
Geonames ID: 3703443
Year established: 2014
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request: UNICyT is member of: Consejo de Rectores de Panamá - CRP (http://www.consejo.ac.pa/miembros.html), Asociación de Universidades Particulares de Panamá - AUPPA (https://auppa.org.pa/universidades-integrantes/), Instituto de Investigaciones de AUPPA - IdIA (https://idia.org.pa/contacto/).

**Comment by adambuttrick** [comment]
Small, career training focused university in Panama. Independent, top-level entity. Research outputs appear primarily to be pedagogical articles by faculty and staff, but are otherwise legitimate.

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=Euqf5h8AAAAJ; https://scholar.google.com/citations?user=nd-sPw8AAAAJ; https://scholar.google.com/citations?user=2v9WZGcAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-9252-8835 ; https://orcid.org/0000-0001-7128-3595 ; https://orcid.org/0000-0001-5347-3221

**Comment by arthurpsmith** [comment]
Agreed, plenty of entries in Google Scholar using this as an affiliation (though almost all seem to be Spanish-language articles). Should be in ROR.
