### ISSUE TITLE
Add a new organization to ROR: Phenomics Australia  

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#51]
Summary of request: Add a new organization to ROR

Name of organization: Phenomics Australia  
Website: http://australianphenomics.org.au/
Link to publications: https://phenomicsaustralia.org.au/acknowledge-us/
Type: Government
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Canberra
Country: Australia
Geonames ID: 2172517
Other information about this request:

**Comment by carlyrobinson** [comment]
Research organization - provides research infrastructure and models. Has team specific to Phenomics Australia. Couldn't find publications or used as affiliation or in acknowledgements.

**Comment by KellyStathis** [comment]
Sorry @mariagould—I'm not sure what happened here, I didn't mean to close this!

**Comment by adambuttrick** [comment]
Spoke with ARDC on our community call and they need this added in order to begin research and funding acknowledgements. Falls within the scope of previous curation discussion about trusted groups providing verified requests for new organizations.

This now has ORCID and publication affiliation usage as well:

https://link.springer.com/article/10.1007/s00335-021-09912-1
https://orcid.org/0000-0002-1708-0401

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0201hm243 in release v1.0.
