### ISSUE TITLE
Add a new organization to ROR: Population Health Research Network

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#52]
Summary of request: Add a new organization to ROR

Name of organization: Population Health Research Network
Website: https://www.phrn.org.au/
Link to publications: https://www.phrn.org.au/publications/research-publications/
Type: Government
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000404871567
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: PHRN
Related organizations: 
City: Crawley
Country: Australia
Geonames ID: 10041014
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree that this organization is associated with research. Seems like a data aggregator and repository. Also can not find used as an affiliation for acknowledgement.

**Comment by adambuttrick** [comment]
Spoke with ARDC on our community call and they need this added in order to begin research and funding acknowledgements. Falls within the scope of previous curation discussion about trusted groups providing verified requests for new organizations.

Now has publication and ORCID affiliation usage as well:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8480827/
https://orcid.org/0000-0001-9097-7066
https://orcid.org/0000-0002-8523-4265
