### ISSUE TITLE
Add a new organization to ROR: 
 
Kathmandu Cancer Center

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#523]
Summary of request: Add a new organization to ROR
Name of organization: Kathmandu Cancer Center
Website: https://kccrc.org/
Link to publications: https://doi.org/10.1016/j.jtct.2022.02.011
Organization type: Healthcare
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0005 0398 4006
GRID ID: 
Crossref Funder ID: 
Aliases: Kathmandu Cancer Hospital
Labels:
Acronym/abbreviation: KCC; KCCH
Related organizations: 
City: Kathmandu
Country: Nepal
Geonames ID: 1283240
Year established: 2015
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Cancer treatment and research facility in Nepal. Solid publication affiliation usage and acknowledged in related journal articles. Should be added to ROR.

Publication affiliation usage: http://thegmj.com/index.php/1/article/view/18 ; https://link.springer.com/chapter/10.1007/978-981-15-0073-2_36 
Google Scholar affiliation_usage: https://scholar.google.com/citations?user=kZ73P58AAAAJ
ORCID affiliation_usage: https://orcid.org/0000-0001-7950-3222 ; https://orcid.org/0000-0002-8992-5194
issue_references: None

**Comment by arthurpsmith** [comment]
I removed the wikidata id from the metadata listing as the entry has been deleted for lack of supporting info. I've seen this happen several times lately, I wonder if some third-party service is trying to register these institutions in various different databases but not doing it quite right?

Otherwise this looks fine to me, definitely a real health-care institution with some research activity, should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04shkzd26 in release v1.1.
