### ISSUE TITLE
Modify the information in an existing ROR record: 
Fundación Seneca https://ror.org/03q68pf65


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#535]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Fundación Seneca
ROR ID: https://ror.org/03q68pf65
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Fundación Séneca - Agencia de Ciencia y Tecnología de la Región de Murcia

Other information about this request: 
Update: change.name==Fundación Séneca - Agencia de Ciencia y Tecnología de la Región de Murcia; add.aliases==f SeNeCa;$

**Comment by adambuttrick** [comment]
While it's not our standard practice to use the full form of the name as the primary value, this request is from the organization, so I think it's okay to approve. Appears on their site (https://fseneca.es/web/contacto). Should probably also add "f SeNeCa" as an alias, since it's used so much in their branding.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
