### ISSUE TITLE
Add a new organization to ROR: 
 
Znanstvenoraziskovalni center Slovenske akademije znanosti in umetnosti

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#537]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Research Centre of the Slovenian Academy of Sciences and Arts
Website: https://www.zrc-sazu.si/
Link to publications: https://ojs.zrc-sazu.si/; https://omp.zrc-sazu.si/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: Q15977604
ISNI ID: 0000 0001 2176 5262
GRID ID: 
Crossref Funder ID: https://www.crossref.org/members/prep/2363
Aliases: Scientific Research Centre of the Slovenian Academy of Science and Arts
Labels: Znanstvenoraziskovalni center Slovenske akademije znanosti in umetnosti*Slovenian
Acronym/abbreviation: ZRC SAZU
Related organizations: https://ror.org/04evj0n95 (parent)
City: Ljubljana
Country: Slovenia
Geonames ID: 3196359
Year established: 1981
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Research institute subsidiary of the Slovenian Academy of Sciences and Arts (https://ror.org/04evj0n95). Publishes open access book and journals (https://zalozba.zrc-sazu.si/en) and is used as an affiliation on publications. While not expressly a top-level entity, appears in scope for ROR because of its outputs.

Publication affiliation usage: https://revije.ff.uni-lj.si/MuzikoloskiZbornik/article/download/9794/9306 ; https://elpub.episciences.org/5530/pdf ; https://d1wqtxts1xzle7.cloudfront.net/39928769/Fran_The_Next_Generation_Slovenian_Dictionary_Portal-with-cover-page-v2.pdf?Expires=1646941113&Signature=VRCqg0MQiOAUpoICPh8HS-9VGvrleOVhhBdEK4g8OCcl8NFJzVdYNZp-678SzjoGES0AVkxFuXNj5owcQsJ~1~68jLWCTeQPlc2k15orRBLt-hsaUtll1HR~Iba0oe1qjmXeMBSI0VZItAYcCqBFBflSep-m~gFDc1sOFAVjz6iHBnHfnnQdD8V34jeJZL4gqwxciRjQTPDySfyZEzp6JjZ5igl54Z0renDLKpb4G9SVfVeQPTTii-aVMKo9gm6ZVmJJvPPsIwBNHN4Jwtn7foshMOoKmjBzM25lvL~4o5KbCJwmcIr7xpf49uSCCn1M1-qxFr~7SXSJE1o9TsT4ow__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA

ORCID affiliation usage: https://orcid.org/0000-0001-8918-6814 ; https://orcid.org/0000-0002-9990-0775 ; https://orcid.org/0000-0003-2511-8921

**Comment by adambuttrick** [comment]
A question related to this record is whether this organizations subsidiary institutes (https://www.zrc-sazu.si/en/enote) should have their own ROR IDs. Some, such as the Jovan Hadži Institute of Biology, have their own Wikidata and ISNI entries (https://www.wikidata.org/wiki/Q12785900) and are use as part of compound affiliations with this organization (e.g. https://www.ufz.de/export/data/10/129754_Oedippus_26.pdf#page=9)

**Comment by mariagould** [comment]
I believe this organization already has a ROR ID: https://ror.org/04zvj8c18

**Comment by adambuttrick** [comment]
Closing as duplicate request.
