### ISSUE TITLE
Add a new organization to ROR: 
 
Herbarium MACB

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#538]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Herbarium MACB
Website: https://biologicas.ucm.es/herbario-macb
Link to publications: https://doi.org/10.15468/dl.jqa227
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Herbario MACB
Labels:
Acronym/abbreviation: MACB
Related organizations: 
City: Madrid
Country: Spain
Year established: 1968
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility

Other information about this request:

**Comment by adambuttrick** [comment]
Herbarium that exists as part of the Complutense University of Madrid's (https://ror.org/02p0gd045) Department of Biology. Not a top-level entity, nor can I find any affiliation usage. Its staff all use the university affiliation. That being said, I'm hesitant to dismiss on this basis alone because according to their site, they do produce datasets of digitized plant material used by researchers. My inclination is to reach out to them for additional context about their request, but I would like others to also weigh in. Use case is similar to the university museum discussed last meeting.

**Comment by adambuttrick** [comment]
Adding additional context from #540 to this request: contributions to DISSCO (https://www.dissco.eu/) appear to require a ROR ID, so the department level collections are seeking them out to identify their data contributions.

**Comment by adambuttrick** [comment]
Closing per comment on #540. Spoke with DiSSCo staff and the department staff over email. They advised using the university's ROR ID for their DiSSCo contributions.
