### ISSUE TITLE
Add a new organization to ROR: 
 
Entomology Collection UCME 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#540]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Entomology Collection UCME 
Website: ucme.bioucm.es
Link to publications: ucme.bioucm.es
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/User:UCMEcol
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Colección de Entomología UCME
Labels:
Acronym/abbreviation: UCME
Related organizations: Complutense University of Madrid
City: Madrid
Country: España
Year established: 1980
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility

Other information about this request: Required to access https://www.dissco.eu/

**Comment by adambuttrick** [comment]
Entomology collection that exists as part of the Complutense University of Madrid's (https://ror.org/02p0gd045) Department of Biology. Not a top-level entity. Staff  use the university affiliation. That being said, I'm hesitant to dismiss on this basis alone because according to their site, they do produce datasets and it looks as if DISSCO is requiring ROR for members.

**Comment by adambuttrick** [comment]
Spoke with DiSSCo staff and the department staff over email. They advised using the university's ROR ID for their DiSSCo contributions. Closing as out of scope.
