### ISSUE TITLE
Add a new organization to ROR: 
 
Perth Children's Hospital

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#571]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Perth Children's Hospital
Website: https://pch.health.wa.gov.au/
Link to publications: https://doi.org/10.2337/dc18-2448; https://doi.org/10.1210/clinem/dgab614; https://doi.org/10.2337/dc21-0304; doi:10.1210/clinem/dgaa768
Organization type: Healthcare (A medical care facility such as hospital or clinic. Excludes medical schools, which should be categorized as “Education”)
Wikipedia page: https://en.wikipedia.org/wiki/Perth_Children%27s_Hospital
Wikidata ID: Q48769668
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:
Acronym/abbreviation: PCH
Related organizations: https://ror.org/04ec98z42 (related)
City: Perth
Country: Australia
Geonames ID: 2063523
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request: I need PCH added to the ROR database, so that I can complete a submission to an online journal using the Hindawi site

**Comment by arthurpsmith** [comment]
Yes, this seems to have been created as a replacement for the Princess Margaret one. When we deprecate it would be nice if there was a way to indicate the new one as a replacement somehow. Otherwise no objections to creating this new record.

Oh I notice ISNI has a "Perth Childrens' Hospital Foundation" - 0000 0004 6085 514X and several records for sub-units of the hospital, but nothing for the hospital itself. Not sure what the relationship is there but I guess we can leave ISNI out of this for now.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/015zx6n37 in release v1.1.
