### ISSUE TITLE
Add a new organization to ROR: 
 
Universidad de la Ciudad de Buenos Aires 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#589]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Universidad de la Ciudad de Buenos Aires 
Website: https://www.udelaciudad.edu.ar
Link to publications: The university is still very new
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Unicaba 
Labels:
Acronym/abbreviation: UCIUDAD
Related organizations: 
City: Buenos Aires 
Country: Argentina
Geonames ID: 3435910
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility

Other information about this request: It is a very new public university that will soon start research activities.

**Comment by adambuttrick** [comment]
Argentinian university established in 2018 through a legislative act by the autonomous, district-level government of Buenos Aires. No publication affiliation usage I can find, although a fair amount of secondary academic references to the organization. It's not exactly too new or out of scope for ROR, but at a nebulous threshold of being established because of the lack of research outputs.

Secondary academic references: https://ri.conicet.gov.ar/bitstream/handle/11336/123671/CONICET_Digital_Nro.19ea5a8e-cdb4-47b9-b94b-95801fd2f784_A.pdf?sequence=2&isAllowed=y ; https://d1wqtxts1xzle7.cloudfront.net/59609261/Estado_Neoliberal__Marginalidad_y_Crisis_de_Soberania_Educativa20190608-49474-8oy7ug-with-cover-page-v2.pdf?Expires=1648796942&Signature=T4WkNt9fnT1ZRWBSIQ5CVUdO~x91WUb6bWAfz6SXRUe7bgsf0Ppr5JYgGV-Z-NUfpn7r-k~s9q0~fe9Be827Umxifm~91vctUw-TzdXsLC7GmtysdGUQ4m3wztYJrVG4YXC4GB5kmQgJvq4eySFc4UjdY9vFTLZ9~i5E23PlEAakzgTGzqKkL0g9-qzkUoqm9o~MGhgZHFT~j8qb9ifvD44KQIl5NPoRqgEG6QoqUa-bIZ56OQ2j7pkjnrZaf4h0~Y~NuZDOepIbRtc9645xY7On95eh3S0ykEoYc9DdSiIY4cPRtG5jovl0V5xXzKwzLNETjEwIDM8xJirPgRFvTw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00g2qdz89 in release v1.1.
