### ISSUE TITLE
Add a new organization to ROR: 
 
 Kent and Medway Medical School

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#593]
Summary of request: Add a new organization to ROR

Name of organization:  Kent and Medway Medical School
Website: https://kmms.ac.uk
Link to publications: https://doi.org/10.1111/tct.13445
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Kent_and_Medway_Medical_School
Wikidata ID: Q54817808
ISNI ID: 0000 0004 9332 7968
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: KMMS
Related organizations: University of Kent https://ror.org/00xkeyj56 (parent) ; Canterbury Christ Church University https://ror.org/0489ggv38 (parent)
City: City of Canterbury
Country: United Kingdom
Geonames ID: 2653877
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, For my purposes as a publisher I can only speak confidently that we will use this to match affiliations, but it could have other uses listed above.

Other information about this request: This is on behalf of the university, who asked that we ensure that Kent and Medway is identified for our Read-and-Publish workflow. Please feel free to contact me for any questions. Thanks so much!

**Comment by adambuttrick** [comment]
While medical schools are still indeterminately in scope for ROR, this particular organization was created as a joint venture between the University of Kent (https://ror.org/00xkeyj56) and Canterbury Christ Church University (https://ror.org/0489ggv38). Since neither broader affiliation is used on publications (e.g. https://doi.org/10.2337/db21-0686), I think this in scope.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=g4viFr4AAAAJ; https://scholar.google.com/citations?user=kPZDgBYAAAAJ; https://scholar.google.com/citations?user=hTzuEjgAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-6293-2960 ; https://orcid.org/0000-0003-0140-2880 ; https://orcid.org/0000-0002-9137-2517
issue_references: None

**Comment by arthurpsmith** [comment]
Looks good. I tracked down an ISNI id for this also.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/049p9j193 in release v1.1.
