### ISSUE TITLE
Add a new organization to ROR - Johns Hopkins University School of Advanced International Studies

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6108]
Summary of request: Add a new organization to ROR

Name of organization: Johns Hopkins University School of Advanced International Studies
Website: http://www.sais-jhu.edu
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Paul_H._Nitze_School_of_Advanced_International_Studies
Wikidata ID: Q1352632
ISNI ID: 0000 0001 2155 6866
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Paul H. Nitze School of Advanced International Studies; JHU School of Advanced International Studies; Johns Hopkins University SAIS; Johns Hopkins SAIS; School of Advanced International Studies
Labels:
Acronym/abbreviation: JHU SAIS; SAIS
Related organizations: https://ror.org/02nckqd02 (child) https://ror.org/05ajv1r64 (child)
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 1943
Other information about this request:

**Comment by adambuttrick** [comment]
Request submitted via email as part of a larger ISNI reconciliation project. JHU SAIS effectively operates like a campus entity out of Washington DC and has its own international schools and programs, two of which (https://ror.org/02nckqd02 and https://ror.org/02nckqd02) already exist in ROR. It may makes sense to add given these circumstances, but would appreciate a second review.

**Comment by arthurpsmith** [comment]
I don't know if you tried running your usual affiliation scripts on this? I did some querying via Google Scholar and though it seems hard to narrow down (SAIS gives lots of irrelevant French responses, and the spelled out name is a bit ambiguous too) from what I spot-checked it looks like people from this school typically do *not* mention Johns Hopkins in their affiliations - rather it's just SAIS. Also SAIS publishes at least one journal - https://en.wikipedia.org/wiki/The_SAIS_Review_of_International_Affairs - so could be considered a publisher in its own right. And it seems to be at least sometimes using a slightly separated website URL (sais-jhu rather than sais.jhu). On the other hand there doesn't seem to be any independent funding source for the school - it's clearly administratively entirely under Johns Hopkins. Though it does have its own "board" ?

Anyway, on the weight of the issues here and the long-standing nature as a separated campus of the university, it seems fine to me to create a separate ROR id for this school.

**Comment by arthurpsmith** [comment]
Since this has been hanging around for several months I'm not going to bump it immediately to "ready for sign-off", in case some other consideration may have changed in the meantime. But feel free to do so if it seems ready to you (anybody else!)

**Comment by adambuttrick** [comment]
@arthurpsmith Thanks for reviewing! No additional consideration needed. I've been working directly with the requestor, so am familiar with the ins and outs of this one.
