### ISSUE TITLE
Project: Additional Czech Academy of Sciences Record Updates

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#784]
The Czech Academy of Sciences has identified five additional records that should be updated to correspond to the rest of the set. The five records that need updating are:

- https://ror.org/039nazg33  - Institute of Entomology
- https://ror.org/0436nxt45  - Institute of Hydrobiology (ASCR)
- https://ror.org/05rhyza23 - Institute of Parasitology
- https://ror.org/00jr65m43 - Institute of Plant Molecular Biology
- https://ror.org/02tz8r820 - Institute of Soil Biology

In addition, the records should identify https://ror.org/05pq4yn02 as a parent.

**Comment by adambuttrick** [comment]
@janderova @jdvorak001 If you have the opportunity, it would be much appreciated if you could review the updated records linked below. Hoping that you can verify that these correctly represent the Czech Academy of Sciences Biology Centre institutes:

https://github.com/ror-community/ror-updates/commit/69245222910d6f8cfe568c7ef7ba4f3d1bb200b9?diff=unified

**Comment by janderova** [comment]
@adambuttrick @jdvorak001 I will let you know about that I have to gain more information from the institutes.

**Comment by jdvorak001** [comment]
@adambuttrick , thank you. Those five institutes had existed as independent institutes of the Czech Academy of Sciences in the past. In 2006 they were merged to form the Biology Centre and they seem to continue their existence as divisions within that centre (cf. https://www.bc.cas.cz/en/about-us/ and the organizational structure chart file). I'd therefore suggest having the Biology Centre (https://ror.org/05pq4yn02) as the parent, not the entire CAS.

**Comment by janderova** [comment]
@jdvorak001 @adambuttrick Please wait with correction, we would prefer have just one institute - Biology Centre but I have to discuss it with the Institutes.

**Comment by jdvorak001** [comment]
@janderova I wouldn't advise requesting a removal of those institutes. They were and probably still are relevant for the affiliation use-case of ROR, given the inertia which affiliation statements seem to have.

**Comment by janderova** [comment]
@adambuttrick @jdvorak001

Hi Adam,

thank you for your patience.
I have got answer from director of Biology center: they want to have just one ROR for whole institution - Biology Centre, because the five institutes -  Institute of Entomology https://ror.org/0436nxt45 - Institute of Hydrobiology (ASCR), https://ror.org/05rhyza23 - Institute of Parasitology, https://ror.org/00jr65m43 - Institute of Plant Molecular Biology, https://ror.org/02tz8r820 - Institute of Soil Biology
they are now just departments.

ROR - https://ror.org/05pq4yn02
They want to have these names - the primary name - Biology Centre of the Czech Academy of Sciences, 
other names - Biologické centrum AV ČR, v. v. i.; Czech Academy of Sciences, Biology Centre; BC AV ČR

If you can change Czech website to English - https://www.bc.cas.cz/en/homepage/
add wikidata Q8310408 please.

Thank you for you time.
Have a nice day
Katerina Janderova

**Comment by adambuttrick** [comment]
@janderova Thank you for these details! I will create separate issues to reflect these changes.

**Comment by adambuttrick** [comment]
#936 and #938 address these changes. Closing.
