### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Aerodynamics

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8469]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Aerodynamics
Website: 
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: State Key Lab of Aerodynamics
Acronym/abbreviation: 
Labels: 空气动力学国家重点实验室*Chinese
Related organizations: https://github.com/ror-community/ror-updates/issues/8479 (successor)
City: Mianyang
Country: China
Geonames ID: 1800627
Year established: 
Other information about this request: Inactive. Part of #8123. Supporting units: China Aerodynamics Research and Development Center. http://18th_cfd.cars.org.cn/home/articleList?type=fund&aid=1379

**Comment by adambuttrick** [comment]
@huangjqq This was submitted with #8479 as its inactive predecessor organization. Although they have different names in Chinese, I'm wondering if they were truly distinct from each other, given that they are in the same place and have the same parent. Could you take a look?

**Comment by huangjqq** [comment]
I'm going to agree with your assessment that it's more of a name change (in Chinese) than really a predecessor/successor relationship -- I would list it as an alias. This name translates to "State Key Laboratory of Aerodynamic Science" while #8479 has a little fun extra "State Key Laboratory of Aerodynamic Science _and Technology_", but since it retained the same English name, I'd say it's the same organization with just very slight rebranding.

**Comment by adambuttrick** [comment]
Updated https://github.com/ror-community/ror-updates/issues/8479 to reflect curator review.
